title: Gitiwan's Blog
tagline: 지어지고 있는 블로그
description: Getting better every single moment.

author:
  name:   Song-Zi Vong
  url:    https://twitter.com/vfvong
  avatar: https://avatars.githubusercontent.com/u/97170774

plugins:
  - jekyll-paginate

paginate: 2

categories_path: /categories/
tags_path: /tags/