title: 지완성
tagline: 지어지는 블로그
description: "참고: 제가알기론"

author:
  name:   G-WAN
  url:    https://gitiwan.github.io/
  avatar: ./logo.png

plugins:
  - jekyll-paginate

paginate: 5

categories_path: /categories/
gits_path: /gits/