title: 지완성
tagline: 지어지는 블로그
description: Getting better \n every single moment.

author:
  name:   G-wan Han
  url:    https://twitter.com/vfvong
  avatar: https://avatars.githubusercontent.com/u/97170774

plugins:
  - jekyll-paginate

paginate: 2

categories_path: /categories/
tags_path: /tags/